name: "propagate_meta"
description: propagate_meta module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - propagate_meta:
      description: propagate_meta module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information\n          e.g. `[ id:'test', single_end:false ]`
    - l0_dir:
        type: file
        description: |
          Input l0_dir
        pattern: "*"
    - level:
        type: value
        description: |
          Input level
output:
  - meta:
      - level:
          type: value
          description: |
            Output level
      - */.panoseti-meta:
          type: file
          description: |
            Output */.panoseti-meta
          pattern: "*/.panoseti-meta"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
