name: utils_nfcore_analysis_pipeline
description: Pipeline-specific utilities
keywords:
  - panoseti
  - analysis
  - pipeline
components:
  - completionsummary
  - utils_nextflow_pipeline
  - utils_nfcore_pipeline
  - utils_nfschema_plugin

authors:
  - "@nraultwang"

output: []
