contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #analysis channel"
    url: https://nfcore.slack.com/channels/analysis
    about: Discussion about the panoseti/analysis pipeline
