name: ingest
description: Local subworkflow ingest for panoseti_analysis
keywords:
  - panoseti
  - analysis
  - pipeline
components:
  - pff/to/zarr
  - build/hk
  - calibrate/ph
  - calibrate/img
  - build/manifest
  - l1/quicklook

authors:
  - "@nraultwang"

output: []
