name: pff_to_zarr
description: Local module pff_to_zarr for panoseti_analysis
keywords:
  - panoseti
tools:
  - pff_to_zarr:
      description: pff_to_zarr component
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: "['MIT']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@nraultwang"
maintainers:
  - "@nraultwang"
