name: "pff_to_zarr"
description: pff_to_zarr module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - pff_to_zarr:
      description: pff_to_zarr module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information\n          e.g. `[ id:'test', single_end:false ]`
    - obs_dir:
        type: file
        description: |
          Input obs_dir
        pattern: "*"
output:
  - l0:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information\n            e.g. `[ id:'test', single_end:false ]`
      - *.zarr:
          type: file
          description: |
            Output *.zarr
          pattern: "*.zarr"
      - l0_lineage.json:
          type: file
          description: |
            Output l0_lineage.json
          pattern: "l0_lineage.json"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
