name: classify_cloud_cpu
description: Local module classify_cloud_cpu for panoseti_analysis
keywords:
  - panoseti
tools:
  - classify_cloud_cpu:
      description: classify_cloud_cpu component
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: "['MIT']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@nraultwang"
maintainers:
  - "@nraultwang"
