name: "classify_cloud_cpu"
description: classify_cloud_cpu module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - classify_cloud_cpu:
      description: classify_cloud_cpu module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - l1_store:
        type: file
        description: |
          Input l1_store
        pattern: "*"
  - - model_file:
        type: file
        description: |
          Input model_file
        pattern: "*"
  - - model_json:
        type: file
        description: |
          Input model_json
        pattern: "*"
output:
  - store:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.zarr":
          type: file
          description: |
            Output *.zarr
          pattern: "*.zarr"
  - lineage:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.json":
          type: file
          description: |
            Output *.json
          pattern: "*.json"
  - quicklook:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.png":
          type: file
          description: |
            Output *.png
          pattern: "*.png"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
