name: "build_manifest"
description: build_manifest module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - build_manifest:
      description: build_manifest module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - run_id:
        type: value
        description: |
          Input run_id
    - lineage:
        type: file
        description: |
          Input lineage
        pattern: "*"
    - level:
        type: value
        description: |
          Input level
output:
  - manifest:
      - level:
          type: value
          description: |
            Output level
      - manifest.json:
          type: file
          description: |
            Output manifest.json
          pattern: "manifest.json"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
