name: "classify_cloud_ray"
description: classify_cloud_ray module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - classify_cloud_ray:
      description: classify_cloud_ray module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - run_id:
        type: value
        description: |
          Input run_id
    - l1_stores:
        type: file
        description: |
          Input l1_stores
        pattern: "*"
  - - model_file:
        type: file
        description: |
          Input model_file
        pattern: "*"
  - - model_json:
        type: file
        description: |
          Input model_json
        pattern: "*"
output:
  - stores:
      - *.zarr:
          type: file
          description: |
            Output *.zarr
          pattern: "*.zarr"
  - lineage:
      - run_id:
          type: value
          description: |
            Output run_id
      - lineage.json:
          type: file
          description: |
            Output lineage.json
          pattern: "lineage.json"
  - quicklook:
      - *.png:
          type: file
          description: |
            Output *.png
          pattern: "*.png"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
