name: ml
description: Local subworkflow ml for panoseti_analysis
keywords:
  - panoseti
  - analysis
  - pipeline
components:
  - classify_cloud
  - build/manifest

authors:
  - "@nraultwang"

output: []
