name: "l1_quicklook"
description: l1_quicklook module for PANOSETI analysis
keywords:
  - panoseti
tools:
  - l1_quicklook:
      description: l1_quicklook module
      homepage: https://github.com/panoseti/analysis
      documentation: https://github.com/panoseti/analysis
      tool_dev_url: https://github.com/panoseti/analysis
      doi: ""
      licence: "['MIT']"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information\n          e.g. `[ id:'test', single_end:false ]`
    - l0_store:
        type: file
        description: |
          Input l0_store
        pattern: "*"
    - l1_store:
        type: file
        description: |
          Input l1_store
        pattern: "*"
output:
  - quicklook:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information\n            e.g. `[ id:'test', single_end:false ]`
      - *.png:
          type: file
          description: |
            Output *.png
          pattern: "*.png"
  - versions:
      - versions.yml:
          type: file
          description: |
            Output versions.yml
          pattern: "versions.yml"
authors:
  - "@nicolas"
