name: classify_cloud
description: Local subworkflow classify_cloud for panoseti_analysis
keywords:
  - panoseti
  - analysis
  - pipeline
components:
  - classify_cloud

authors:
  - "@nraultwang"

output: []
